#!/usr/bin/env node
// Regenerates the per-group color CSS custom properties from the single
// source of truth in src/data/palette.js, and writes them into
// src/css/_palette.generated.css. styles.css @imports that file.
//
// Run:  npm run build:palette   (or: node scripts/build-palette.mjs)

import { PAL } from '../src/data/palette.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'src', 'css', '_palette.generated.css');

const lines = [];
lines.push('/* AUTO-GENERATED by scripts/build-palette.mjs — do not edit by hand. */');
lines.push('/* Edit src/data/palette.js and re-run `npm run build:palette`. */');
lines.push(':root{');
for (const g of Object.keys(PAL)) {
  for (const pos of ['0', '1', '2', '3']) {
    const { bg, fg } = PAL[g][pos];
    lines.push(`  --g${g}${pos}:${bg};`);
    lines.push(`  --t${g}${pos}:${fg};`);
  }
}
lines.push('}');

writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out} (${Object.keys(PAL).length} groups × 4 shades).`);
